version: '3.9'

services:

  bullsandcowsbot:
    container_name: bullsandcowsbot
    image: bullsandcowsbot:latest
    env_file:
      - extra_vars.env
    restart: always
    volumes:
    - type: bind
      source: ${PWD}/bot_stat.sqlite
      target: /bot/bot_stat.sqlite
